<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\common\common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="OpenTK.dll.config" />
  </ItemGroup>
</Project>
